### ISSUE TITLE
Add color to bullets for folders beyond the first 11

### ISSUE THREAD

**Issue by ahaghgoo** [mhauken/fever#1]
Hi, 

I first want to say that this is such a incredible upgrade to the former design of Fever°.  I am absolutely loving it!  

I just have one issue with the way it's rendering comment blocks.  I've uploaded screenshots and linked them below, but I do not know how to go about and fixing them.  I appreciate your time and consideration on this issue!

Best, 
Afshin 

![screen shot 2013-12-29 at 21 43 46](https://f.cloud.github.com/assets/1308002/1820952/d931080e-7115-11e3-8065-22b29161f1cb.png)
![screen shot 2013-12-29 at 21 43 30](https://f.cloud.github.com/assets/1308002/1820954/d9374c96-7115-11e3-9d05-6ca6caf7572b.png)
![screen shot 2013-12-29 at 21 43 59](https://f.cloud.github.com/assets/1308002/1820953/d93741a6-7115-11e3-9f1b-fbbe7b594630.png)

**Comment by mhauken** [comment]
Thanks! That's great to hear!
How does this look in the regular fever-design?

These look like block-quotes and I've therefore given them a slight indentation, a bit bluer and italic. You can change this according to your preferences here and export as css: https://github.com/mhauken/fever/blob/master/scss/_typo.scss#L18-L22. 

Marius

**Comment by ahaghgoo** [comment]
I apologize for not thanking you for this!  I sincerely appreciate it!  I've been using this all year and it's awesome!!!

I'm wondering how I can do three things: 
1.  Add color to bullets for folders beyond the first 11. 
2.  How to modify to load this for iPad use. 
3.  How to modify the font (I'm wanting to apply the Neutraface font as I believe it would work perfectly with your design!

Thanks again for the consideration and Happy Holidays!!

**Comment by mhauken** [comment]
Hi, @ahaghgoo !
Great to hear!
1. I have now updated the code (45b7e23d89c339a33610c2b3a639e14183249b92) to support more than 11 folders.
2. This version loads on my iPad. It's loading another stylesheet on iPhone however..
3. You can add the fontstack that you want to [reader.scss here](https://github.com/mhauken/fever/blob/d583d6a07213edf162265d3d386b7cb48e78c092/reader.scss#L9-L10) and compile the scss to css again.

**Comment by ahaghgoo** [comment]
Marius, 

You are awesome!!!  Thank you so much for this! 

-A

## 

Afshin Haghgoo 
ahaghgoo@gmail.com
